image: maven:3.8.6

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml"
  MAVEN_OPTS: "Dmaven.repo.local=m2/repository"

cache:
  paths:
    - .m2/repository
    - target/

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

before_script:
  - chmod +x mvnw

test:
  stage: test
  script: ./mvnw test


build:
  stage: build
  script: ./mvnw package -DskipTests
  artifacts:
    paths:
      - target/vendas-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:
    - echo "Deploy teste"
  only:
    - main
